This Message Was Sent By KaBoom! v2.0.
Date: 30/01/2000
Time: 19:30:04
To: habit@pcnet.com.br
From: Jubileu 2000
Server Used: mail.nettravel.com.br
Priority: High
CC:
drogamil@nettravel.com.br
jadernorte@juina-fox.com.br
uniaodolar@juina-fox.com.br
autosomjn@juina-fox.com.br
webmaster@nettravel.com.br
webmaster@juina-fox.com.br
webmaster@pcnet.com.br
webmaster@speedweb.com.br
webmaster@enter-net.com.br
scopio@juina-fox.com.br
visao@nettravel.com.br
lacamp@zaz.com.br
Message Body: 
Prezado usuario

viemos através desta para solicitar a divulgação do Jubileu do Ano 2000, colocando no vosso site a logomarca do Jubileu (em anexo)junto ao nosso link www.jubileu.com.br.


Lembramos que no ano 2000, um momento marcante da humanidade, além da entrada no novo milênio, celebram-se os 2000 anos da era Cristã. O Jubileu, indulgência promovida pela Igreja Católica é a major expressão deste acontecimento, sendo o maior evento da história da humanidade temos uma lembrança viva deste momento especial que é representado pela Medalha Oficial do Jubileu.


Lembrando que colocando o brasão e o link, além de ajudar na divulgação do Jubileu, através do nosso produto, você está contribuindo ao Fundo de Solidariedade do Vaticano, que sem dúvida reverterá em obras de beneficência aos pobres e necessitados do mundo inteiro.

Certos de que poderão colaborar, ficamos à disposição para eventuais esclarecimentos.


Diretor de Marketing




--------------------------------------------------------------------------------



