/* This temp source file was generated by hbmk2 tool. */
/* You can safely delete it. */

#include "hbapi.h"

HB_FUNC_EXTERN( LETO );

void _hb_lnk_ForceLink_hbmk( void )
{
   HB_FUNC_EXEC( LETO );
}

