/* C source generated by Harbour */

#include "hbvmpub.h"
#include "hbinit.h"

HB_FUNC_INIT( RDDINIT );
HB_FUNC_EXTERN( DBFNTX );
HB_FUNC_EXTERN( DBFCDX );
HB_FUNC_EXTERN( DBFNSX );
HB_FUNC( RDDSYS );

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_RDDSYS )
{ "RDDINIT$", { HB_FS_INIT | HB_FS_LOCAL }, { HB_INIT_FUNCNAME( RDDINIT ) }, NULL },
{ "DBFNTX", { HB_FS_PUBLIC }, { HB_FUNCNAME( DBFNTX ) }, NULL },
{ "DBFCDX", { HB_FS_PUBLIC }, { HB_FUNCNAME( DBFCDX ) }, NULL },
{ "DBFNSX", { HB_FS_PUBLIC }, { HB_FUNCNAME( DBFNSX ) }, NULL },
{ "RDDSYS", { HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL }, { HB_FUNCNAME( RDDSYS ) }, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_RDDSYS, "", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_RDDSYS
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_RDDSYS )
   #include "hbiniseg.h"
#endif

HB_FUNC_INIT( RDDINIT )
{
	static const HB_BYTE pcode[] =
	{
		36,28,0,7
	};

	hb_vmExecute( pcode, symbols );
}

HB_FUNC( RDDSYS )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}
